routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::get('/cache', function () {

    \Illuminate\Support\Facades\Artisan::call('key:generate');
//    \Illuminate\Support\Facades\Artisan::call('vendor:publish --provider=Maatwebsite\Excel\ExcelServiceProvider');
    \Illuminate\Support\Facades\Artisan::call('storage:link');
    \Illuminate\Support\Facades\Artisan::call('cache:clear');
    \Illuminate\Support\Facades\Artisan::call('config:clear');
    \Illuminate\Support\Facades\Artisan::call('view:clear');
    \Illuminate\Support\Facades\Artisan::call('route:clear');
    \Illuminate\Support\Facades\Artisan::call('config:cache');
    \Illuminate\Support\Facades\Artisan::call('migrate');

    return 'Commands run successfully.';
});

Auth::routes(['register' => false]);

Route::get('/home', 'HomeController@index')->name('home');

Route::middleware('auth')->group(function () {
    Route::resource('consignee', 'ConsigneeController');
    Route::resource('carriers', 'CarrierController');
    Route::resource('contracts', 'ContractController');
    Route::resource('consignment', 'ConsignmentController');
    Route::resource('consignment_detail', 'ConsignmentDetailController');
    Route::resource('notify_party', 'NotifyPartyController');
    Route::resource('port', 'PortController');
    Route::resource('shipper', 'ShipperController');
    Route::resource('shipping_co', 'ShippingCoController');
    Route::resource('supplier', 'SupplierController');
    Route::resource('instruction', 'InstructionController');
    Route::resource('reports', 'ReportingController');

    Route::name('ajax.')->prefix('ajax')->group(function () {
        Route::get('getStates/{country_id}', 'AjaxController@getStates')->name('get_states');
        Route::get('getCitiesByCountry/{country_id}', 'AjaxController@getCitiesByCountry')->name('get_cities_by_country');
        Route::get('getCitiesByState/{state_id}', 'AjaxController@getCitiesByState')->name('get_cities_by_state');
        Route::get('getEmail/{email_id}', 'AjaxController@getEmail')->name('get_email');
        Route::put('emailRead/{email_id}', 'AjaxController@emailRead')->name('email_read');
        Route::post('newEmail', 'AjaxController@newEmail')->name('new_email');
        Route::post('forwardEmail', 'AjaxController@forwardEmail')->name('forward_email');
        Route::post('replyEmail', 'AjaxController@replyEmail')->name('reply_email');
        Route::post('emailInvoice', 'AjaxController@emailInvoice')->name('email_invoice');
        Route::post('emailDocuments', 'AjaxController@emailDocuments')->name('email_documents');
        Route::get('instruction/{id}/invoice/download', 'AjaxController@downloadInvoice')->name('download_invoice');
        Route::get('instruction/{id}/si/download', 'AjaxController@downloadSI')->name('download_si');
        Route::get('instruction/{id}/vgm/download', 'AjaxController@downloadVGM')->name('download_vgm');
        Route::post('instruction/{id}/items/save', 'AjaxController@saveItems')->name('save_items');
        Route::put('instruction/{id}/consignee/save', 'AjaxController@saveConsignee')->name('save_consignee');
        Route::put('instruction/{id}/notify/save', 'AjaxController@saveNotify')->name('save_notify');
        Route::post('bookingConfirmation', 'AjaxController@bookingConfirmation')->name('booking_confirmation');
        Route::post('trackingInfo', 'AjaxController@trackingInfo')->name('tracking_info');
        Route::get('getConsignment/{instruction_id}', 'AjaxController@getConsignment')->name('get_consignment');
        Route::get('getTrackingUrl//{carrier_id}', 'AjaxController@getTrackingURL')->name('get_tracking_url');
    });

    /* Extra Functions Routes */
    Route::get('instruction/{id}/email', 'InstructionController@emails')->name('instruction.emails');
    Route::get('instruction/{id}/email/{email_id}', 'InstructionController@showEmail')->name('instruction.email.show');
    Route::get('instruction/{id}/consigment', 'InstructionController@consignment')->name('instruction.consignment');
    Route::get('instruction/{id}/complete', 'InstructionController@complete')->name('instruction.complete');
    Route::get('report/download', 'ReportingController@downloadReport')->name('reports.download');

});

/**
 * Webhook Routes
 */
Route::post('webhook/receive_email','WebhookController@receiveEmail');

Route::get('profile', 'UserController@index');
Route::get('profile/create', 'UserController@create');
Route::post('profile/store', 'UserController@store');
Route::get('profile/show/{id}', 'UserController@show');
Route::get('profile/edit/{id}', 'UserController@edit');
Route::post('profile/update/{id}', 'UserController@update');
Route::delete('profile/destroy/{id}', 'UserController@destroy');

// Route::get('download/excel', 'ExportExcelController@export');
// Route::post('download/excel', 'ExportExcelController@export');
// Route::get('download/excel/file', 'ExportExcelController@excel');
Route::get('container', 'ConsignmentController@index');
Route::post('container/excel', 'ConsignmentController@export');
Route::get('consignee-wise', 'ConsigneeController@showConsignee');
Route::post('consignee-wise/excel', 'ConsigneeController@export');
Route::get('report/contract', 'EtaController@index')->name('reports.contract');
Route::post('eta/excel', 'EtaController@export');
Route::get('item', 'ConsignmentDetailController@index');
Route::post('item/excel', 'ConsignmentDetailController@export');

app/Port.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Port extends Model
{
    use SoftDeletes;
    public function country()
    {
    	return $this->belongsTo(Country::class);
    }

    public function state()
    {
    	return $this->belongsTo(State::class);
    }

    public function city()
    {
    	return $this->belongsTo(City::class);
    }
}

app/Http/Controllers/PortController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Port;
use App\Country;
use App\State;
use App\City;
use Validator;

class PortController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $port_detail = Port::all();
        return view('port.index')->with(['port_detail' => $port_detail]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $countries          = Country::all();
        return view('port.create')->with(['countries' => $countries]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $messages = [
            'name.unique'         => 'Port with Same Name Already Exists',
            'country_id.required' => 'Please Select country',  
            'city_id.required'    => 'Please Select city'
          ];
        Validator::make($request->all(), [
            'name'                    => 'required|unique:ports,name|max:255',
            // 'phone'                   => 'required|unique:ports,phone',
            // 'primary_email'           => 'required|email|unique:ports,primary_email',
            // 'postal_code'             => 'required',
            'country_id'              => 'sometimes|exists_or_null:countries,id',
            'city_id'                 => 'sometimes|exists_or_null:cities,id',
            'address'                 => 'sometimes',
        ], $messages)->validate();

        $port_detail                  = new Port;
        $port_detail->name            = $request->name;
        // $port_detail->phone           = $request->phone;
        // $port_detail->primary_email   = $request->primary_email;
        // $port_detail->postal_code     = $request->postal_code;
        $port_detail->country_id      = $request->country_id;
        $port_detail->city_id         = $request->city_id;
        $port_detail->address         = $request->address;
        $port_detail->save();

        session(['toaster_data' => ['type' => "success", 'message' => "Successfully Added."]]);
        return redirect()->route('port.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $port_detail        = Port::findOrFail($id);
        $countries          = Country::all();
        return view('port.show')->with(['port_detail' => $port_detail, 'countries' => $countries]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $port_detail        = Port::findOrFail($id);
        $countries          = Country::all();
        return view('port.edit')->with(['port_detail' => $port_detail, 'countries' => $countries]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $idport_detail
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $port_detail   = Port::findOrFail($id);

        $messages = [
            'name.unique'         => 'Port with Same Name Already Exists',
            'country_id.required' => 'Please Select country',  
            'city_id.required'    => 'Please Select city'
        ];
        Validator::make($request->all(), [
            'name'          => 'required|unique:ports,name,'. $id .'|max:255', 
            // 'phone'         => 'required',
            // 'primary_email' => 'required|email',
            // 'postal_code'   => 'required',
            'country_id'    => 'sometimes|exists_or_null:countries,id',
            'city_id'       => 'sometimes|exists_or_null:cities,id',
            'address'       => 'sometimes',
        ], $messages)->validate();

        $port_detail->name            = $request->name;
        $port_detail->phone           = $request->phone;
        $port_detail->primary_email   = $request->primary_email;
        $port_detail->postal_code     = $request->postal_code;
        $port_detail->country_id      = $request->country_id;
        $port_detail->city_id         = $request->city_id;
        $port_detail->address         = $request->address;
        $port_detail->save();

        session(['toaster_data' => ['type' => "success", 'message' => "Successfully Updated."]]);
        return redirect()->route('port.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $port_detail = Port::findOrFail($id);

        $port_detail->name           = $port_detail->name . ' - Removed:' . time();
        $port_detail->primary_email  = $port_detail->primary_email . ' - Removed:' . time();
        $port_detail->save();

        $port_detail->delete();

        session(['toaster_data' => ['type' => "success", 'message' => "Successfully Removed."]]);
        return redirect()->route('port.index');
    }
}

resources/views/port/create.blade.php
@extends('adminlte::page')

@section('title', 'List - Port')

@section('content_header')
<h1>Port Details</h1>
@endsection

@section('content')
<div class="row">
      <div class="col-md-12">
          <!-- general form elements -->
          <div class="box box-primary">
            <div class="box-header with-border">
              <h3 class="box-title">Add Port Details</h3>
            </div>
            <!-- /.box-header -->
            <!-- form start -->
           <form action="{{ route('port.store') }}" method="post">
             @csrf
              <div class="box-body">
                <div class="form-group {{ $errors->has('name') ? 'has-error' : ''}}">
                  <label for="name">Port Name *</label>
                  <input type="text" class="form-control {{ $errors->has('name') ? 'has-error' : ''}} " name="name" id="name" placeholder="Port Name" value="{{ old('name') }}">
                  @if ($errors->has('name'))
                    <span class="help-block text-danger">{{ $errors->first('name') }}</span>
                  @endif
                </div>
                {{-- <div class="form-group {{ $errors->has('phone') ? 'has-error' : ''}}">
                  <label for="phone">Port Phone</label>
                  <input type="text" class="form-control" name="phone" id="phone" placeholder="Port Phone" value="{{ old('phone') }}">
                  @if ($errors->has('phone'))
                    <span class="help-block text-danger">{{ $errors->first('phone') }}</span>
                  @endif
                </div>
                 <div class="form-group {{ $errors->has('primary_email') ? 'has-error' : ''}}">
                  <label for="primary_email">Port Primary Email</label>
                  <input type="text" class="form-control" name="primary_email" id="primary_email" placeholder="Port Primary Email" value="{{ old('primary_email') }}">
                   @if ($errors->has('primary_email'))
                    <span class="help-block text-danger">{{ $errors->first('primary_email') }}</span>
                  @endif
                </div>
                <div class="form-group {{ $errors->has('postal_code') ? 'has-error' : ''}}">
                  <label for="postal_code">Postal Code </label>
                  <input type="text" class="form-control" name="postal_code" id="postal_code" placeholder="Postal Code" value="{{ old('postal_code') }}">
                   @if ($errors->has('postal_code'))
                    <span class="help-block text-danger">{{ $errors->first('postal_code') }}</span>
                  @endif
                </div> --}}
                <div class="form-group {{ $errors->has('country_id') ? 'has-error' : ''}}">
                  <label for="country_id">Country</label>
                  <select class="form-control" id="country_id" name="country_id">
                    <option value="">Select Country</option>
                    @foreach ($countries as $country)
                     <option value="{{$country->id}}" {{ $country->id == old('country_id') ? 'selected' : ''}}>{{$country->name }}</option>
                    @endforeach
                  </select>
                   @if ($errors->has('country_id'))
                    <span class="help-block text-danger">{{ $errors->first('country_id') }}</span>
                  @endif
                </div>
                <div class="form-group {{ $errors->has('city_id') ? 'has-error' : ''}}">
                  <label for="city_id">City</label>
                 <select class="form-control" id="city_id" name="city_id">
                    <option value="">Select City</option>
                  </select>
                  @if ($errors->has('city_id'))
                    <span class="help-block text-danger">{{ $errors->first('city_id') }}</span>
                  @endif
                </div>
                {{-- <div class="form-group {{ $errors->has('address') ? 'has-error' : ''}}">
                  <label for="category_title">Port Address</label>
                  <input type="text" class="form-control" name="address" id="address" placeholder="Port Address" value="{{ old('address') }}">
                   @if ($errors->has('address'))
                    <span class="help-block text-danger">{{ $errors->first('address') }}</span>
                  @endif
                </div> --}}
              </div>
              <!-- /.box-body -->
              <div class="box-footer">
                <button type="submit" class="btn btn-primary">Save</button>
              </div>
            </form>
          </div>
          <!-- /.box -->
        </div>
      </div>
@endsection

@push('js')
  <script type="text/javascript">
     $(function(){
        $("#country_id").change(function(){
          var countryId = $(this).val();
          if ( $('countryId').val() != '' ) 
          {
            var endPoint  = "{{ route('ajax.get_states', ['COUNTRY_ID']) }}".replace("COUNTRY_ID", countryId);
            $.ajax({
                type: "GET",
                url: endPoint,
                dataType: "json",
                cache: true,
                success: function(response)
                {
                  $("#state_id").empty();
                  $("#state_id").html("<option value=''>Select State</option>");
                  $.each(response, function(i, item) {
                    $('#state_id').append($('<option>', {value:item.id, text:item.name}));
                  });
                }
            });
            endPoint  = "{{ route('ajax.get_cities_by_country', ['COUNTRY_ID']) }}".replace("COUNTRY_ID", countryId);
            $.ajax({
                type: "GET",
                url: endPoint,
                dataType: "json",
                cache: true,
                success: function(response)
                {
                  $("#city_id").empty();
                  $("#city_id").html("<option value=''>Select City</option>");
                  $.each(response, function(i, item) {
                    $('#city_id').append($('<option>', {value:item.id, text:item.name}));
                  });
                }
            });
          }
        });
         $("#state_id").change(function(){
            var stateId = $(this).val();
            if ( $('stateId').val() != '' ) {
            var endPoint  = "{{ route('ajax.get_cities_by_state', ['STATE_ID']) }}".replace("STATE_ID", stateId);
            $.ajax({
                type: "GET",
                url: endPoint,
                dataType: "json",
                cache: true,
                success: function(response)
                {
                  $("#city_id").empty();
                  $("#city_id").html("<option value=''>Select City</option>");
                  $.each(response, function(i, item) {
                    $('#city_id').append($('<option>', {value:item.id, text:item.name}));
                  });
                }
            });
          }
        });
        $("#country_id").trigger('change');
        $("#state_id").trigger('change');
        setTimeout(function(){
          var old_state_id  = '{{ old('state_id') }}';
          var old_city_id   = '{{ old('city_id') }}';
          if(old_state_id != '')
          {
            $("#state_id option[value='" + old_state_id + "']").prop('selected', true);
          }
          if(old_city_id != '')
          {
            $("#city_id option[value='" + old_city_id + "']").prop('selected', true);
          }
        }, 1000);
    });
  </script>
@endpush

resources/views/port/edit.blade.php
@extends('adminlte::page')

@section('title', 'List - Port')

@section('content_header')
<h1>Port Deatils</h1>
@endsection

@section('content')
<div class="row">
      <div class="col-md-12">
          <!-- general form elements -->
          <div class="box box-primary">
            <div class="box-header with-border">
              <h3 class="box-title">Add Port Details</h3>
            </div>
            <!-- /.box-header -->
            <!-- form start -->
           <form action="{{ route('port.update', $port_detail->id) }}" method="post">
             @csrf
             @method('put')
              <div class="box-body">
                <div class="form-group {{ $errors->has('name') ? 'has-error' : ''}}">
                  <label for="name">Port Name *</label>
                  <input type="text" class="form-control {{ $errors->has('name') ? 'has-error' : ''}} " name="name" id="name" placeholder="Port Name" value="{{ old('name', $port_detail->name) }}">
                  @if ($errors->has('name'))
                    <span class="help-block text-danger">{{ $errors->first('name') }}</span>
                  @endif
                </div>
                {{-- <div class="form-group {{ $errors->has('phone') ? 'has-error' : ''}}">
                  <label for="phone">Port Phone</label>
                  <input type="text" class="form-control" name="phone" id="phone" placeholder="Port Phone" value="{{ old('phone', $port_detail->phone) }}">
                  @if ($errors->has('phone'))
                    <span class="help-block text-danger">{{ $errors->first('phone') }}</span>
                  @endif
                </div>
                 <div class="form-group {{ $errors->has('primary_email') ? 'has-error' : ''}}">
                  <label for="primary_email">Port Primary Email</label>
                  <input type="text" class="form-control" name="primary_email" id="primary_email" placeholder="Port Primary Email" value="{{ old('primary_email', $port_detail->primary_email) }}">
                   @if ($errors->has('primary_email'))
                    <span class="help-block text-danger">{{ $errors->first('primary_email') }}</span>
                  @endif
                </div>
                <div class="form-group {{ $errors->has('postal_code') ? 'has-error' : ''}}">
                  <label for="postal_code">Postal Code </label>
                  <input type="text" class="form-control" name="postal_code" id="postal_code" placeholder="Postal Code" value="{{ old('postal_code', $port_detail->postal_code) }}">
                   @if ($errors->has('postal_code'))
                    <span class="help-block text-danger">{{ $errors->first('postal_code') }}</span>
                  @endif
                </div> --}}
                <div class="form-group {{ $errors->has('country_id') ? 'has-error' : ''}}">
                  <label for="country_id">Country</label>
                  <select class="form-control" id="country_id" name="country_id">
                    <option value="">Select Country</option>
                    @foreach ($countries as $country)
                     <option value="{{$country->id}}" {{ $country->id == old('country_id', $port_detail->country_id) ? 'selected' : ''}}>{{$country->name }}</option>
                    @endforeach
                  </select>
                   @if ($errors->has('country_id'))
                    <span class="help-block text-danger">{{ $errors->first('country_id') }}</span>
                  @endif
                </div>
                <div class="form-group {{ $errors->has('city_id') ? 'has-error' : ''}}">
                  <label for="city_id">City</label>
                 <select class="form-control" id="city_id" name="city_id">
                    <option value="">Select City</option>
                  </select>
                  @if ($errors->has('city_id'))
                    <span class="help-block text-danger">{{ $errors->first('city_id') }}</span>
                  @endif
                </div>
                {{-- <div class="form-group {{ $errors->has('address') ? 'has-error' : ''}}">
                  <label for="category_title">Port Address</label>
                  <input type="text" class="form-control" name="address" id="address" placeholder="Comapny Address" value="{{ old('address', $port_detail->address) }}">
                   @if ($errors->has('address'))
                    <span class="help-block text-danger">{{ $errors->first('address') }}</span>
                  @endif
                </div> --}}
              </div>
              <!-- /.box-body -->
              <div class="box-footer">
                <button type="submit" class="btn btn-primary">Save</button>
              </div>
            </form>
          </div>
          <!-- /.box -->
        </div>
      </div>
@endsection

@push('js')
  <script type="text/javascript">
     $(function(){
        $("#country_id").change(function(){
          var countryId = $(this).val();
          if ( $('countryId').val() != '' ) 
          {
            var endPoint  = "{{ route('ajax.get_states', ['COUNTRY_ID']) }}".replace("COUNTRY_ID", countryId);
            $.ajax({
                type: "GET",
                url: endPoint,
                dataType: "json",
                cache: true,
                success: function(response)
                {
                  $("#state_id").empty();
                  $("#state_id").html("<option value=''>Select State</option>");
                  $.each(response, function(i, item) {
                    $('#state_id').append($('<option>', {value:item.id, text:item.name}));
                  });
                }
            });
            endPoint  = "{{ route('ajax.get_cities_by_country', ['COUNTRY_ID']) }}".replace("COUNTRY_ID", countryId);
            $.ajax({
                type: "GET",
                url: endPoint,
                dataType: "json",
                cache: true,
                success: function(response)
                {
                  $("#city_id").empty();
                  $("#city_id").html("<option value=''>Select City</option>");
                  $.each(response, function(i, item) {
                    $('#city_id').append($('<option>', {value:item.id, text:item.name}));
                  });
                }
            });
          }
        });
         $("#state_id").change(function(){
            var stateId = $(this).val();
            if ( $('stateId').val() != '' ) {
            var endPoint  = "{{ route('ajax.get_cities_by_state', ['STATE_ID']) }}".replace("STATE_ID", stateId);
            $.ajax({
                type: "GET",
                url: endPoint,
                dataType: "json",
                cache: true,
                success: function(response)
                {
                  $("#city_id").empty();
                  $("#city_id").html("<option value=''>Select City</option>");
                  $.each(response, function(i, item) {
                    $('#city_id').append($('<option>', {value:item.id, text:item.name}));
                  });
                }
            });
          }
        });
        $("#country_id").trigger('change');
        $("#state_id").trigger('change');
        setTimeout(function(){
          var old_state_id  = '{{ old('state_id', $port_detail->state_id) }}';
          var old_city_id   = '{{ old('city_id', $port_detail->city_id) }}';
          if(old_state_id != '')
          {
            $("#state_id option[value='" + old_state_id + "']").prop('selected', true);
          }
          if(old_city_id != '')
          {
            $("#city_id option[value='" + old_city_id + "']").prop('selected', true);
          }
        }, 1000);
    });
  </script>
@endpush

resources/views/port/index.blade.php
@extends('adminlte::page')

@section('title', 'List - Port Detials')

@section('content_header')
  <h1>Port Details</h1>
@endsection

@section('content')
      <div class="row">
        <div class="col-xs-12">
          <div class="box">
            <div class="box-header">
              <a href="{{ route('port.create') }}"><button class="btn btn-primary add-btn-right">Add New</button></a>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
              <table id="shippingCompany" class="table table-bordered table-hover">
                <thead>
                <tr>
                  <th>ID</th>
                  <th>Port Name</th>
                  <th>Country</th>
                  <th>City</th>
                  {{-- <th>Address</th> --}}
                  <th>Action</th>
                </tr>
                </thead>
                <tbody>
                   @foreach ($port_detail as $port_details)
                  <tr>
                    <td>{{ $port_details->id }}</td>
                    <td>{{ $port_details->name }}</td>
                    <td>{{ $port_details->country->name ?? '-' }}</td>
                    <td>{{ $port_details->city->name ?? '-' }}</td>
                    {{-- <td>{{ $port_details->address ?? '-' }}</td> --}}
                    <td class="text-center">
                      <div class="btn-group action-buttons"> 
                         <a href="{{ route('port.show', $port_details->id) }}" >
                          <button class="btn btn-xs btn-success" type="button" data-toggle="tooltip" title="Show"><i class="fa fa-eye"></i>
                          </button>
                        </a>
                        <a href="{{ route('port.edit', $port_details->id) }}">
                          <button class="btn btn-xs btn-primary" type="button" data-toggle="tooltip" title="Edit"><i class="fa fa-pencil"></i>
                          </button>
                        </a> 
                        <form action="{{ route('port.destroy',$port_details->id) }}" method="post" class="form-inline remove">
                          @csrf
                          @method('delete')
                          <button class="btn btn-xs btn-danger" type="submit" data-toggle="tooltip" title="Remove"><i class="fa fa-times"></i>
                          </button>
                        </form> 
                    </div>
                    </td>
                  </tr>
                  @endforeach
                </tbody>
              </table>
            </div>
            <!-- /.box-body -->
          </div>
        </div>
        <!-- /.col -->
      </div>
@endsection
@push('css')
<style type="text/css">
  .action-buttons form {
   display: inline-block !important ;
}
</style>
@endpush
@push('js')
<script type="text/javascript">
  $('#shippingCompany').DataTable({
      'paging'      : true,
      'lengthChange': false,
      'searching'   : true,
      'ordering'    : true,
      'info'        : true,
      'autoWidth'   : false,
      "order"       : [[ 0, "desc" ]]
  });
  $('form.remove').submit(function(e){
    var node = $(this);
    e.preventDefault();
    if(confirm("Are you sure? You really want to delete this?"))
    {
      node.unbind('submit');
      node.submit();
    }
  });
</script>
@endpush