routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::get('/cache', function () {

    \Illuminate\Support\Facades\Artisan::call('key:generate');
//    \Illuminate\Support\Facades\Artisan::call('vendor:publish --provider=Maatwebsite\Excel\ExcelServiceProvider');
    \Illuminate\Support\Facades\Artisan::call('storage:link');
    \Illuminate\Support\Facades\Artisan::call('cache:clear');
    \Illuminate\Support\Facades\Artisan::call('config:clear');
    \Illuminate\Support\Facades\Artisan::call('view:clear');
    \Illuminate\Support\Facades\Artisan::call('route:clear');
    \Illuminate\Support\Facades\Artisan::call('config:cache');
    \Illuminate\Support\Facades\Artisan::call('migrate');

    return 'Commands run successfully.';
});

Auth::routes(['register' => false]);

Route::get('/home', 'HomeController@index')->name('home');

Route::middleware('auth')->group(function () {
    Route::resource('consignee', 'ConsigneeController');
    Route::resource('carriers', 'CarrierController');
    Route::resource('contracts', 'ContractController');
    Route::resource('consignment', 'ConsignmentController');
    Route::resource('consignment_detail', 'ConsignmentDetailController');
    Route::resource('notify_party', 'NotifyPartyController');
    Route::resource('port', 'PortController');
    Route::resource('shipper', 'ShipperController');
    Route::resource('shipping_co', 'ShippingCoController');
    Route::resource('supplier', 'SupplierController');
    Route::resource('instruction', 'InstructionController');
    Route::resource('reports', 'ReportingController');

    Route::name('ajax.')->prefix('ajax')->group(function () {
        Route::get('getStates/{country_id}', 'AjaxController@getStates')->name('get_states');
        Route::get('getCitiesByCountry/{country_id}', 'AjaxController@getCitiesByCountry')->name('get_cities_by_country');
        Route::get('getCitiesByState/{state_id}', 'AjaxController@getCitiesByState')->name('get_cities_by_state');
        Route::get('getEmail/{email_id}', 'AjaxController@getEmail')->name('get_email');
        Route::put('emailRead/{email_id}', 'AjaxController@emailRead')->name('email_read');
        Route::post('newEmail', 'AjaxController@newEmail')->name('new_email');
        Route::post('forwardEmail', 'AjaxController@forwardEmail')->name('forward_email');
        Route::post('replyEmail', 'AjaxController@replyEmail')->name('reply_email');
        Route::post('emailInvoice', 'AjaxController@emailInvoice')->name('email_invoice');
        Route::post('emailDocuments', 'AjaxController@emailDocuments')->name('email_documents');
        Route::get('instruction/{id}/invoice/download', 'AjaxController@downloadInvoice')->name('download_invoice');
        Route::get('instruction/{id}/si/download', 'AjaxController@downloadSI')->name('download_si');
        Route::get('instruction/{id}/vgm/download', 'AjaxController@downloadVGM')->name('download_vgm');
        Route::post('instruction/{id}/items/save', 'AjaxController@saveItems')->name('save_items');
        Route::put('instruction/{id}/consignee/save', 'AjaxController@saveConsignee')->name('save_consignee');
        Route::put('instruction/{id}/notify/save', 'AjaxController@saveNotify')->name('save_notify');
        Route::post('bookingConfirmation', 'AjaxController@bookingConfirmation')->name('booking_confirmation');
        Route::post('trackingInfo', 'AjaxController@trackingInfo')->name('tracking_info');
        Route::get('getConsignment/{instruction_id}', 'AjaxController@getConsignment')->name('get_consignment');
        Route::get('getTrackingUrl//{carrier_id}', 'AjaxController@getTrackingURL')->name('get_tracking_url');
    });

    /* Extra Functions Routes */
    Route::get('instruction/{id}/email', 'InstructionController@emails')->name('instruction.emails');
    Route::get('instruction/{id}/email/{email_id}', 'InstructionController@showEmail')->name('instruction.email.show');
    Route::get('instruction/{id}/consigment', 'InstructionController@consignment')->name('instruction.consignment');
    Route::get('instruction/{id}/complete', 'InstructionController@complete')->name('instruction.complete');
    Route::get('report/download', 'ReportingController@downloadReport')->name('reports.download');

});

/**
 * Webhook Routes
 */
Route::post('webhook/receive_email','WebhookController@receiveEmail');

Route::get('profile', 'UserController@index');
Route::get('profile/create', 'UserController@create');
Route::post('profile/store', 'UserController@store');
Route::get('profile/show/{id}', 'UserController@show');
Route::get('profile/edit/{id}', 'UserController@edit');
Route::post('profile/update/{id}', 'UserController@update');
Route::delete('profile/destroy/{id}', 'UserController@destroy');

// Route::get('download/excel', 'ExportExcelController@export');
// Route::post('download/excel', 'ExportExcelController@export');
// Route::get('download/excel/file', 'ExportExcelController@excel');
Route::get('container', 'ConsignmentController@index');
Route::post('container/excel', 'ConsignmentController@export');
Route::get('consignee-wise', 'ConsigneeController@showConsignee');
Route::post('consignee-wise/excel', 'ConsigneeController@export');
Route::get('report/contract', 'EtaController@index')->name('reports.contract');
Route::post('eta/excel', 'EtaController@export');
Route::get('item', 'ConsignmentDetailController@index');
Route::post('item/excel', 'ConsignmentDetailController@export');

app/Http/Controllers/ShippingCoController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\ShippingCompany;
use App\Country;
use App\State;
use App\City;
use Validator;

class ShippingCoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $shipping_companies = ShippingCompany::all();
        return view('shipping_co.index')->with(['shipping_companies' => $shipping_companies]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $countries = Country::all();

        return view('shipping_co.create')->with(['countries' => $countries]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $messages = [
            'country_id.required' => 'Please Select country',
            'city_id.required' => 'Please Select city',
        ];
        Validator::make($request->all(), [
            'name' => 'required|unique:shipping_companies,name|max:255',
            'phone' => 'sometimes|nullable|unique:shipping_companies,phone',
            'primary_email' => 'required|email|unique:shipping_companies,primary_email',
            'postal_code' => 'sometimes',
            'country_id' => 'sometimes|nullable|exists:countries,id',
            'city_id' => 'sometimes|nullable|exists:cities,id',
            'address' => 'required',
        ], $messages)->validate();

        $shipping_company = new ShippingCompany;
        $shipping_company->name = $request->name;
        $shipping_company->phone = $request->phone;
        $shipping_company->primary_email = $request->primary_email;
        $shipping_company->postal_code = $request->postal_code;
        $shipping_company->tracking_url = $request->tracking_url;
        $shipping_company->country_id = $request->country_id;
        $shipping_company->city_id = $request->city_id;
        $shipping_company->address = $request->address;
        $shipping_company->save();

        session(['toaster_data' => ['type' => "success", 'message' => "Successfully Added."]]);
        return redirect()->route('shipping_co.index');
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $shipping_company = ShippingCompany::findOrFail($id);
        $countries = Country::all();
        return view('shipping_co.show')->with(['shipping_company' => $shipping_company, 'countries' => $countries]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $shipping_company = ShippingCompany::findOrFail($id);
        $countries = Country::all();
        return view('shipping_co.edit')->with(['shipping_company' => $shipping_company, 'countries' => $countries]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $shipping_company = ShippingCompany::findOrFail($id);

        $messages = [
            'country_id.required' => 'Please Select country',
            'city_id.required' => 'Please Select city',
        ];
        Validator::make($request->all(), [
            'name' => 'required|unique:shipping_companies,name,' . $id . '|max:255',
            'phone' => 'sometimes|nullable|unique:shipping_companies,phone,' . $id . '',
            'primary_email' => 'required|email|unique:shipping_companies,primary_email,' . $id . '',
            'postal_code' => 'sometimes',
            'country_id' => 'sometimes|nullable|exists:countries,id',
            'city_id' => 'sometimes|nullable|exists:cities,id',
            'address' => 'required',
        ], $messages)->validate();

        $shipping_company->name = $request->name;
        $shipping_company->phone = $request->phone;
        $shipping_company->primary_email = $request->primary_email;
        $shipping_company->postal_code = $request->postal_code;
        $shipping_company->tracking_url = $request->tracking_url;
        $shipping_company->country_id = $request->country_id;
        $shipping_company->city_id = $request->city_id;
        $shipping_company->address = $request->address;
        $shipping_company->save();

        session(['toaster_data' => ['type' => "success", 'message' => "Successfully Updated."]]);
        return redirect()->route('shipping_co.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $shipping_companies = ShippingCompany::findOrFail($id);

        $shipping_companies->name = $shipping_companies->name . ' - Removed:' . time();
        $shipping_companies->primary_email = $shipping_companies->primary_email . ' - Removed:' . time();
        $shipping_companies->save();

        $shipping_companies->delete();

        session(['toaster_data' => ['type' => "success", 'message' => "Successfully Removed."]]);
        return redirect()->route('shipping_co.index');
    }
}

resources/views/shipping_co/create.blade.php
@extends('adminlte::page')

@section('title', 'List - Shipping Companies')

@section('content_header')
    <h1>Shipping Company</h1>
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">
            <!-- general form elements -->
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Add Shipping Company</h3>
                </div>
                <!-- /.box-header -->
                <!-- form start -->
                <form action="{{ route('shipping_co.store') }}" method="post">
                    @csrf
                    <div class="box-body">
                        <div class="form-group {{ $errors->has('name') ? 'has-error' : ''}}">
                            <label for="name">Company Name *</label>
                            <input type="text" class="form-control {{ $errors->has('name') ? 'has-error' : ''}} "
                                   name="name" id="name" placeholder="Company Name" value="{{ old('name') }}">
                            @if ($errors->has('name'))
                                <span class="help-block text-danger">{{ $errors->first('name') }}</span>
                            @endif
                        </div>
                        <div class="form-group {{ $errors->has('phone') ? 'has-error' : ''}}">
                            <label for="phone">Company Phone</label>
                            <input type="text" class="form-control" name="phone" id="phone" placeholder="Company Phone"
                                   value="{{ old('phone') }}">
                            @if ($errors->has('phone'))
                                <span class="help-block text-danger">{{ $errors->first('phone') }}</span>
                            @endif
                        </div>
                        <div class="form-group {{ $errors->has('primary_email') ? 'has-error' : ''}}">
                            <label for="primary_email">Company Primary Email *</label>
                            <input type="text" class="form-control" name="primary_email" id="primary_email"
                                   placeholder="Company Primary Email" value="{{ old('primary_email') }}">
                            @if ($errors->has('primary_email'))
                                <span class="help-block text-danger">{{ $errors->first('primary_email') }}</span>
                            @endif
                        </div>
                        <div class="form-group {{ $errors->has('postal_code') ? 'has-error' : ''}}">
                            <label for="postal_code">Postal Code </label>
                            <input type="text" class="form-control" name="postal_code" id="postal_code"
                                   placeholder="Postal Code" value="{{ old('postal_code') }}">
                            @if ($errors->has('postal_code'))
                                <span class="help-block text-danger">{{ $errors->first('postal_code') }}</span>
                            @endif
                        </div>
                        <div class="form-group {{ $errors->has('tracking_url') ? 'has-error' : ''}}">
                            <label for="tracking_url">Tracking URL </label>
                            <input type="text" class="form-control" name="tracking_url" id="tracking_url"
                                   placeholder="Tracking URL" value="{{ old('tracking_url') }}">
                            @if ($errors->has('tracking_url'))
                                <span class="help-block text-danger">{{ $errors->first('tracking_url') }}</span>
                            @endif
                        </div>
                        <div class="form-group {{ $errors->has('country_id') ? 'has-error' : ''}}">
                            <label for="country_id">Country</label>
                            <select class="form-control" id="country_id" name="country_id">
                                <option value="">Select Country</option>
                                @foreach ($countries as $country)
                                    <option
                                        value="{{$country->id}}" {{ $country->id == old('country_id') ? 'selected' : ''}}>{{$country->name }}</option>
                                @endforeach
                            </select>
                            @if ($errors->has('country_id'))
                                <span class="help-block text-danger">{{ $errors->first('country_id') }}</span>
                            @endif
                        </div>
                        <div class="form-group {{ $errors->has('city_id') ? 'has-error' : ''}}">
                            <label for="city_id">City</label>
                            <select class="form-control" id="city_id" name="city_id">
                                <option value="">Select City</option>
                            </select>
                            @if ($errors->has('city_id'))
                                <span class="help-block text-danger">{{ $errors->first('city_id') }}</span>
                            @endif
                        </div>
                        <div class="form-group {{ $errors->has('address') ? 'has-error' : ''}}">
                            <label for="address">Company Address *</label>
                            <input type="text" class="form-control" name="address" id="address"
                                   placeholder="Company Address" value="{{ old('address') }}">
                            @if ($errors->has('address'))
                                <span class="help-block text-danger">{{ $errors->first('address') }}</span>
                            @endif
                        </div>
                    </div>
                    <!-- /.box-body -->
                    <div class="box-footer">
                        <button type="submit" class="btn btn-primary">Save</button>
                    </div>
                </form>
            </div>
            <!-- /.box -->
        </div>
    </div>
@endsection

@push('js')
    <script type="text/javascript">
        $(function () {
            $("#country_id").change(function () {
                var countryId = $(this).val();
                if ($('countryId').val() != '') {
                    var endPoint = "{{ route('ajax.get_states', ['COUNTRY_ID']) }}".replace("COUNTRY_ID", countryId);
                    $.ajax({
                        type: "GET",
                        url: endPoint,
                        dataType: "json",
                        cache: true,
                        success: function (response) {
                            $("#state_id").empty();
                            $("#state_id").html("<option value=''>Select State</option>");
                            $.each(response, function (i, item) {
                                $('#state_id').append($('<option>', {value: item.id, text: item.name}));
                            });
                        }
                    });
                    endPoint = "{{ route('ajax.get_cities_by_country', ['COUNTRY_ID']) }}".replace("COUNTRY_ID", countryId);
                    $.ajax({
                        type: "GET",
                        url: endPoint,
                        dataType: "json",
                        cache: true,
                        success: function (response) {
                            $("#city_id").empty();
                            $("#city_id").html("<option value=''>Select City</option>");
                            $.each(response, function (i, item) {
                                $('#city_id').append($('<option>', {value: item.id, text: item.name}));
                            });
                        }
                    });
                }
            });
            $("#state_id").change(function () {
                var stateId = $(this).val();
                if ($('stateId').val() != '') {
                    var endPoint = "{{ route('ajax.get_cities_by_state', ['STATE_ID']) }}".replace("STATE_ID", stateId);
                    $.ajax({
                        type: "GET",
                        url: endPoint,
                        dataType: "json",
                        cache: true,
                        success: function (response) {
                            $("#city_id").empty();
                            $("#city_id").html("<option value=''>Select City</option>");
                            $.each(response, function (i, item) {
                                $('#city_id').append($('<option>', {value: item.id, text: item.name}));
                            });
                        }
                    });
                }
            });
            // $("#country_id").trigger('change');
            // $("#state_id").trigger('change');
            setTimeout(function () {
                var old_state_id = '{{ old('state_id') }}';
                var old_city_id = '{{ old('city_id') }}';
                if (old_state_id != '') {
                    $("#state_id option[value='" + old_state_id + "']").prop('selected', true);
                }
                if (old_city_id != '') {
                    $("#city_id option[value='" + old_city_id + "']").prop('selected', true);
                }
            }, 1000);
        });
    </script>
@endpush

resources/views/shipping_co/edit.blade.php
@extends('adminlte::page')

@section('title', 'List - Shipping Companies')

@section('content_header')
    <h1>Shipping Company</h1>
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">
            <!-- general form elements -->
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Add Shipping Company</h3>
                </div>
                <!-- /.box-header -->
                <!-- form start -->
                <form action="{{ route('shipping_co.update', $shipping_company->id) }}" method="post">
                    @csrf
                    @method('put')
                    <div class="box-body">
                        <div class="form-group {{ $errors->has('name') ? 'has-error' : ''}}">
                            <label for="name">Company Name *</label>
                            <input type="text" class="form-control {{ $errors->has('name') ? 'has-error' : ''}} "
                                   name="name" id="name" placeholder="Company Name"
                                   value="{{ old('name', $shipping_company->name) }}">
                            @if ($errors->has('name'))
                                <span class="help-block text-danger">{{ $errors->first('name') }}</span>
                            @endif
                        </div>
                        <div class="form-group {{ $errors->has('phone') ? 'has-error' : ''}}">
                            <label for="phone">Company Phone</label>
                            <input type="text" class="form-control" name="phone" id="phone" placeholder="Company Phone"
                                   value="{{ old('phone', $shipping_company->phone) }}">
                            @if ($errors->has('phone'))
                                <span class="help-block text-danger">{{ $errors->first('phone') }}</span>
                            @endif
                        </div>
                        <div class="form-group {{ $errors->has('primary_email') ? 'has-error' : ''}}">
                            <label for="primary_email">Company Primary Email *</label>
                            <input type="text" class="form-control" name="primary_email" id="primary_email"
                                   placeholder="Company Primary Email"
                                   value="{{ old('primary_email', $shipping_company->primary_email) }}">
                            @if ($errors->has('primary_email'))
                                <span class="help-block text-danger">{{ $errors->first('primary_email') }}</span>
                            @endif
                        </div>
                        <div class="form-group {{ $errors->has('postal_code') ? 'has-error' : ''}}">
                            <label for="postal_code">Postal Code </label>
                            <input type="text" class="form-control" name="postal_code" id="postal_code"
                                   placeholder="Postal Code"
                                   value="{{ old('postal_code', $shipping_company->postal_code) }}">
                            @if ($errors->has('postal_code'))
                                <span class="help-block text-danger">{{ $errors->first('postal_code') }}</span>
                            @endif
                        </div>
                        <div class="form-group {{ $errors->has('tracking_url') ? 'has-error' : ''}}">
                            <label for="tracking_url">Tracking URL </label>
                            <input type="text" class="form-control" name="tracking_url" id="tracking_url"
                                   placeholder="Tracking URL"
                                   value="{{ old('tracking_url', $shipping_company->tracking_url) }}">
                            @if ($errors->has('tracking_url'))
                                <span class="help-block text-danger">{{ $errors->first('tracking_url') }}</span>
                            @endif
                        </div>
                        <div class="form-group {{ $errors->has('country_id') ? 'has-error' : ''}}">
                            <label for="country_id">Country</label>
                            <select class="form-control" id="country_id" name="country_id">
                                <option value="">Select Country</option>
                                @foreach ($countries as $country)
                                    <option
                                        value="{{$country->id}}" {{ $country->id == old('country_id', $shipping_company->country_id) ? 'selected' : ''}}>{{$country->name }}</option>
                                @endforeach
                            </select>
                            @if ($errors->has('country_id'))
                                <span class="help-block text-danger">{{ $errors->first('country_id') }}</span>
                            @endif
                        </div>
                        <div class="form-group {{ $errors->has('city_id') ? 'has-error' : ''}}">
                            <label for="city_id">City</label>
                            <select class="form-control" id="city_id" name="city_id">
                                <option value="">Select City</option>
                            </select>
                            @if ($errors->has('city_id'))
                                <span class="help-block text-danger">{{ $errors->first('city_id') }}</span>
                            @endif
                        </div>
                        <div class="form-group {{ $errors->has('address') ? 'has-error' : ''}}">
                            <label for="address">Company Address *</label>
                            <input type="text" class="form-control" name="address" id="address"
                                   placeholder="Company Address"
                                   value="{{ old('address', $shipping_company->address) }}">
                            @if ($errors->has('address'))
                                <span class="help-block text-danger">{{ $errors->first('address') }}</span>
                            @endif
                        </div>
                    </div>
                    <!-- /.box-body -->
                    <div class="box-footer">
                        <button type="submit" class="btn btn-primary">Save</button>
                    </div>
                </form>
            </div>
            <!-- /.box -->
        </div>
    </div>
@endsection

@push('js')
    <script type="text/javascript">
        $(function () {
            $("#country_id").change(function () {
                var countryId = $(this).val();
                if ($('countryId').val() != '') {
                    var endPoint = "{{ route('ajax.get_states', ['COUNTRY_ID']) }}".replace("COUNTRY_ID", countryId);
                    $.ajax({
                        type: "GET",
                        url: endPoint,
                        dataType: "json",
                        cache: true,
                        success: function (response) {
                            $("#state_id").empty();
                            $("#state_id").html("<option value=''>Select State</option>");
                            $.each(response, function (i, item) {
                                $('#state_id').append($('<option>', {value: item.id, text: item.name}));
                            });
                        }
                    });
                    endPoint = "{{ route('ajax.get_cities_by_country', ['COUNTRY_ID']) }}".replace("COUNTRY_ID", countryId);
                    $.ajax({
                        type: "GET",
                        url: endPoint,
                        dataType: "json",
                        cache: true,
                        success: function (response) {
                            $("#city_id").empty();
                            $("#city_id").html("<option value=''>Select City</option>");
                            $.each(response, function (i, item) {
                                $('#city_id').append($('<option>', {value: item.id, text: item.name}));
                            });
                        }
                    });
                }
            });
            $("#state_id").change(function () {
                var stateId = $(this).val();
                if ($('stateId').val() != '') {
                    var endPoint = "{{ route('ajax.get_cities_by_state', ['STATE_ID']) }}".replace("STATE_ID", stateId);
                    $.ajax({
                        type: "GET",
                        url: endPoint,
                        dataType: "json",
                        cache: true,
                        success: function (response) {
                            $("#city_id").empty();
                            $("#city_id").html("<option value=''>Select City</option>");
                            $.each(response, function (i, item) {
                                $('#city_id').append($('<option>', {value: item.id, text: item.name}));
                            });
                        }
                    });
                }
            });
            $("#country_id").trigger('change');
            $("#state_id").trigger('change');
            setTimeout(function () {
                var old_state_id = '{{ old('state_id', $shipping_company->state_id) }}';
                var old_city_id = '{{ old('city_id', $shipping_company->city_id) }}';
                if (old_state_id != '') {
                    $("#state_id option[value='" + old_state_id + "']").prop('selected', true);
                }
                if (old_city_id != '') {
                    $("#city_id option[value='" + old_city_id + "']").prop('selected', true);
                }
            }, 1000);
        });
    </script>
@endpush